### ISSUE TITLE
Add `allMarkets()` to `FuseFlywheelCore` to make it compatible with `FusePoolLensSecondary`

### ISSUE THREAD

**Issue by Pczek** [fei-protocol/fuse-flywheel#3]
While implementing a Reward System using the RewardsDistributer we've been relying on the `FusePoolLensSecondary.getUnclaimedRewardsByDistributor()`.
I'm not sure if the goal of a Flywheel is to be used as full replacement for a `RewardsDistributor` but if so it would help if it's fully usable with the these Lens functions as well.

As far as I can tell the only part missing is the `getAllMarkets()` function.

```solidity
  CToken[] public allMarkets;

  function getAllMarkets() external view returns (CToken[] memory) {
    return allMarkets;
  }
```

This would also be quite helpful anyways as the only way currently to check for Rewards of a flywheel to go over each market of a `comptroller.getAllMarkets()` and check against the Flywheel or it's Rewards contract.

And adding a market on the `Flywheel` via `addMarketForRewards(ERC20 market)` is required anyways updating the `marketState`, however not sure how to get all markets from this `mapping` if it's possible.

----

FYI the rari-dapp is also using the Lens and this specific function here:
https://github.com/Rari-Capital/rari-dApp/blob/6ae7f237f749ad3d2c51311c2a611271ca6b80bc/src/hooks/rewards/useUnclaimedFuseRewards.ts#L143-L149

**Comment by Joeysantoro** [comment]
@Pczek yes flywheel is intended to become a full replacement.

Which contract needs allMarkets? the comptroller already has this

**Comment by Pczek** [comment]
Ah that would be awesome!
A I missed putting it in the text as well. It's just in the title.
The `FuseFlywheel` itself. I can prepare a PR for this today. ✌️

**Comment by Joeysantoro** [comment]
> `FusePoolLensSecondary.getUnclaimedRewardsByDistributor()` is calling `getAllMarkets()` on the RewardsDistributors. And as the `FuseFlywheelCore` claims to be a rewards distributor we now need to expose `allStrategies` as `allMarkets` to be compatible.
> 
> ```
>  function allMarkets() external view returns (ERC20[] memory) {
>         return allStrategies;
>  }
> ```

have you tested this? I believe the abi for a storage array is actually 

>  function allMarkets(uint256 index) external view returns (ERC20) {
>         return allStrategies[index];
>  }

the functionality you desire is managed by `getAllMarkets()` which returns the whole array
