### ISSUE TITLE
`FusePoolLensSecondary.getRewardSpeedsByPool()` is Incompatible with `FuseFlywheelCore`

### ISSUE THREAD

**Issue by Pczek** [fei-protocol/fuse-flywheel#7]
`FusePoolLensSecondary.getRewardSpeedsByPool()` is in Compatible with `FuseFlywheelCore` as the Lens is accessing the following mappings of the `RewardsDistributorStorage`

```
  /// @notice The portion of compRate that each market currently receives
  mapping(address => uint256) public compSupplySpeeds;

  /// @notice The portion of compRate that each market currently receives
  mapping(address => uint256) public compBorrowSpeeds;
```

Not sure how we could implement this. I guess we would need to expand the `IFlywheelRewards` interface to provide information of the reward speed of a market.

**Comment by Joeysantoro** [comment]
@Pczek the point of flywheel-v2 is to remove the concept of a "reward speed" in favor of "arbitrary stream"

I don't think backward compatibility will be easy/elegant

**Comment by Pczek** [comment]
Yes, agree that this can become quite ugly.

That's why I asked if the `FuseFlywheel`, should become a compatible replacement for the `RewardsDistributor`
https://github.com/fei-protocol/fuse-flywheel/issues/3#issuecomment-1079513413

Not sure if this is a good idea anymore. Most of all the `FusePoolLensSecondary` function will throw exceptions as it's not interacting with RewardsDistributors but Flywheels as we are adding Flywheels as RewardsDistributors.

https://github.com/fei-protocol/fuse-flywheel/blob/master/src/FuseFlywheelCore.sol#L7

I guess we need to rework the `Lenses` to properly distinguish between `RewardsDistrbutors.isRewardsDistributor` and `FlywheelCore.isFlywheel`.

Otherwise, code using the `FusePoolLensSecondary` interacting with a pool, which has a Flywheel attached will break.
