### ISSUE TITLE
Make a Booster that supports borrowing

### ISSUE THREAD

**Issue by Joeysantoro** [fei-protocol/fuse-flywheel#8]
https://github.com/Rari-Capital/compound-protocol/blob/fuse-final/contracts/RewardsDistributorDelegate.sol#L221

and

https://github.com/Rari-Capital/compound-protocol/blob/fuse-final/contracts/RewardsDistributorDelegate.sol#L271

https://github.com/Rari-Capital/compound-protocol/blob/fuse-final/contracts/RewardsDistributorDelegate.sol#L300

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/
